# This workflow will launch at 00:00 every Sunday
on:
  push:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

name: Scala Steward - Update Scala dependencies

env:
  GRAAL_HOME: /home/runner/.jabba/jdk/graalvm@20.0.0
  SBT_OPTS: -Dsbt.log.noformat=true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: olafurpg/setup-scala@v13
        with:
          java-version: graalvm@20.0.0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.STEWARD_ACTION }}
